# Generated by Django 5.0.4 on 2024-04-05 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=20)),
                ('assign_to', models.CharField(max_length=100)),
                ('deadline', models.DateField(default=datetime.datetime(2024, 5, 5, 16, 29, 9, 705017))),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
