# Generated by Django 5.0.4 on 2024-04-05 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TASK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_create',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 5, 5, 17, 27, 16, 107553)),
        ),
    ]
